name: eShopOnWeb Build and Test

# Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

# Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-eshoponweb-ping123454321  # Ensure correct resource group
  LOCATION: eastus  # Azure location
  TEMPLATE-FILE: infra/webapp.bicep  # Path to your Bicep template
  SUBSCRIPTION-ID: bd70f87e-e3de-4632-b1a6-d77630884ecf  # Your Azure Subscription ID
  WEBAPP-NAME: eshoponweb-webapp51677969  # Ensure unique name for web app

jobs:
  # Build, test, and publish .NET web project in the repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Prepare the runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      # Build the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      # Test the .NET project
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      # Publish the .NET project
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      # Upload the Bicep template as artifacts for the next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    
      # Download the publish files created in the previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app
  
      # Download the Bicep templates from the previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template
        
      # Login to your Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
           
      # Deploy Azure WebApp using Bicep file
      - name: Deploy infrastructure via Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep  # Path to Bicep template
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false
    
      # Publish website to Azure App Service using Azure CLI (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name ${{ env.WEBAPP-NAME }} \
              --resource-group ${{ env.RESOURCE-GROUP }} \
              --src-path .net-app/app.zip --type zip
